### ISSUE TITLE
modbus update

### ISSUE THREAD

**Issue by CannonRS** [olivergregorius/sun2000_modbus#28]
Hello,
is there a plan to update pymodus to 2.5.3 ? I ask because I can't use different pymodbus versions for every tool whats using pymodbus.
Best regards

**Comment by olivergregorius** [comment]
Hi @CannonRS, you're welcome to contribute to this repo.

**Comment by sg26565** [comment]
I've added #36 to upgrade to the latest version of pymodbus.
